### ISSUE TITLE
Multiple users?

### ISSUE THREAD

**Issue by justinmoon** [gashirar/theia-kubernetes#1]
How many users can this support when using helm?

I'm trying to teach a class using Theia. I'd like each student to be provisioned their own container in an automated fashion. 

Is that what Helm does?

Sorry I am kubernetes noob!

**Comment by ab73863** [comment]
@justinmoon ,

Helm is a Kubernetes deloyment and lifecycle manager .It helps in making the deployment of a container over a K8s cluster. So how many independent theia pods that you want to spin up is upto you by running the deployment and service yaml with different app and selector names.

Helm is not specifically controlling on how many independent containers you want.

**Comment by gashirar** [comment]
@ab73863 
Thanks for the comment!
